name: Android CI

on:
  workflow_dispatch: # Elle tetiklemeyi açar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # v3'tü, v4 yaptık (Güncel)
    
    - name: set up JDK 17
      uses: actions/setup-java@v4 # v3'tü, v4 yaptık (Güncel)
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # BURASI ÖNEMLİ: Release yerine Debug alıyoruz ki şifre istemesin
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # HATA VEREN KISIM BURASIYDI (DÜZELTİLDİ)
    - name: Upload APK
      uses: actions/upload-artifact@v4 # v2 idi, v4 yaptık
      with:
        name: app-debug
        # Şifreleme adımını sildiğimiz için direkt dosya yolunu veriyoruz
        path: app/build/outputs/apk/debug/app-debug.apk
